---
title: "MCSimulation"
author: "Sinbad"
date: "01/06/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

MCSim <-function(TransitionMatrix , StartingState){
  
  
  
  
  #TransitionMatrix[CurrentState, ] #this will determine the probability of moving to each state
  
  #StateHistory <- matrix(0, 1 , 11) #creates a column vector of length iterations, to store the "history" of the markov chain.
  
  #StateHistory[1,1] <- StartingState
  
  NumberOfStates <- nrow(TransitionMatrix)
  
  CurrentState <- StartingState
  
  
  for (i in 1:10){
    
    Example <- sample(NumberOfStates , size = 1 , prob = TransitionMatrix[CurrentState , ])
    
    print(Example)
    
    CurrentState <- Example
    
  }
  
}



```




```{r}

MCSim2 <-function(TransitionMatrix , StartingState){
  
  
  
  
  #TransitionMatrix[CurrentState, ] #this will determine the probability of moving to each state
  
  StateHistory <- matrix(1, 1 , 11) #creates a column vector of length iterations, to store the "history" of the markov chain.
  
  StateHistory[1,1] <- StartingState
  
  NumberOfStates <- nrow(TransitionMatrix)
  
  CurrentState <- StartingState
  
  
  for (i in 1:10){
    
    Example <- sample(NumberOfStates , size = 1 , prob = TransitionMatrix[ StateHistory[i] , ])
    
    print(Example)
    
    StateHistory[i+1] <- Example
    
  }
  
}



```




```{r}

MCSim3 <- function(TransitionMatrix, StartingState, length){
  
  
  #TransitionMatrix[CurrentState, ] #this will determine the probability of moving to each state
  
  StateHistory <- StartingState
  
  NumberOfStates <- nrow(TransitionMatrix)
  
  
  
  
  for (i in 1:length){
    
    Example <- sample(NumberOfStates , size = 1 , prob = TransitionMatrix[ StateHistory[i] , ])
    
    StateHistory <- c( StateHistory , Example )
    
  }
  
  return(StateHistory)
  
}
  
  
```



```{r}

IsAbsorbing <- function(TransitionMatrix){
  
  NumberOfStates <- nrow(TransitionMatrix)
  
  abs <- c()
  
  for (i in 1:NumberOfStates){
    
    if(TransitionMatrix[ i , i ] == 1){
      
    
      
      abs <- c(abs, i)
      
      
    }
    
    
  }
  
  return(abs)
}


```



```{r}

MCSim4 <- function(TransitionMatrix, StartingState, length){
  
  
  #TransitionMatrix[CurrentState, ] #this will determine the probability of moving to each state
  
  StateHistory <- StartingState
  
  NumberOfStates <- nrow(TransitionMatrix)
  
  AbStates <- IsAbsorbing(TransitionMatrix)
  
  
  
  for (i in 1:length){
    
    if (any(is.element(AbStates, StateHistory))==TRUE){
      
      print('Early termination as reached an absorbing state')
      
      return(StateHistory)
    }
    
    Example <- sample(NumberOfStates , size = 1 , prob = TransitionMatrix[ StateHistory[i] , ])
    
    StateHistory <- c( StateHistory , Example )
    
  }
  
  return(StateHistory)
  
}
  
  
```



```{r}


MCSim5 <- function(TransitionMatrix, StartingState, length, repetitions){
  
  
  
  reps <- c()
  
  for (i in 1:repetitions){
    
    reps <- cbind(reps , MCSim3(TransitionMatrix, StartingState, length))
    
    
  }
  
  
  return(reps)
  
  
  
}






```




```{r}

MCSim6 <- function(TransitionMatrix, StartingState, length){
  
  
  #TransitionMatrix[CurrentState, ] #this will determine the probability of moving to each state
  
  StateHistory <- StartingState
  
  NumberOfStates <- nrow(TransitionMatrix)
  
  AbStates <- IsAbsorbing(TransitionMatrix)
  
  
  
  for (i in 1:length){
    
    if (any(is.element(AbStates, StateHistory))==TRUE){
      
      
      StateHistory <- LengthFixer(StateHistory, length +1)
      
      return(StateHistory)
    }
    
    Example <- sample(NumberOfStates , size = 1 , prob = TransitionMatrix[ StateHistory[i] , ])
    
    StateHistory <- c( StateHistory , Example )
    
  }
  
  return(StateHistory)
  
}
  
  
```



```{r}


LengthFixer <- function(Vector, DesiredLength){
  
  currentlength <- length(Vector)
  
  difference <- DesiredLength - currentlength
  
  ending <- rep(Vector[currentlength] , difference)
  
  Vector <- c(Vector, ending)
  
  return(Vector)
}
  
  
  



```


```{r}

MCSim7 <- function(TransitionMatrix, StartingState, length, repetitions){
  
  
  
  reps <- c()
  
  for (i in 1:repetitions){
    
    reps <- cbind(reps , MCSim6(TransitionMatrix, StartingState, length))
    
    
  }
  
  
  return(reps)
  
  
  
}






```



```{r}


totalnines <- c()
firstnine <- c()

for (i in 1:10000){
  
  
  
  totalnines <- c(totalnines, is.element(9, testerer2[,i]))
  firstnine <- c(firstnine, match(9 , testerer2[,i]))
  
}

averagenine <- sum(firstnine, na.rm=TRUE) / sum(totalnines)

print(averagenine)
```


```{r}

totaltens <- c()
firstten <- c()

for (i in 1:10000){
  
  
  
  totaltens <- c(totaltens, is.element(10, testerer2[,i]))
  firstten <- c(firstten, match(10 , testerer2[,i]))
  
}

averageten <- sum(firstten, na.rm=TRUE) / sum(totaltens)

print(averageten)


```

```{r}

totalelevens <- c()
firsteleven <- c()

for (i in 1:10000){
  
  
  
  totalelevens <- c(totalelevens, is.element(11, testerer2[,i]))
  firsteleven <- c(firsteleven, match(11 , testerer2[,i]))
  
}

averageeleven <- sum(firsteleven, na.rm=TRUE) / sum(totalelevens)

print(averageeleven)



```

```{r}
binom.test(sum(totalnines) , 10000, 0.3464704)
```

